import { Link } from "react-router-dom";
import { useState, useRef } from 'react';
import { useLocation } from "react-router-dom";
import Information from './Game/Information';
import Choices from './Game/Choices';
import GoogleAd from './GoogleAd';

import getWorldFromUserJSON from '../scripts/story';
import '../styles/play.css';

function Game() {

  const location = useLocation();
  const { userData } = location.state || {}; // safely access state

  let debugUser = userData;
  let debugJSON = JSON.stringify(debugUser);

  /*
    Uses useRef instead of useState, this way world can keeps its methods
    I was having issues with methods being wiped when the state would be serialized
    It might be worth it to refactor how state is handled, and separate logic from it.
    Potentially, state could exist as a single room generated by world.
  */
  const worldRef = useRef(getWorldFromUserJSON(debugJSON));
  const [, forceRender] = useState({});

  const handleChange = (type, value) => {
    const w = worldRef.current;

    // am I understanding best practice? this feels hacky.
    // maybe I should have had a handleChange or handleClick function within each component.
    // will change if time allows.
    
    if (type == "option") {
      w.choosePath(value);
    }

    if (type == "location") {
      w.moveTo(value);
    }

    if (type == "item") {
      w.inspectItem(value);
      w.selectedItem = value;
    }
    
    forceRender({});
  }

  const playerHasItems = (itemKeys) => { // wrapper for world.playerHasItems(). Without this transfers the function but not the inventory information, so it would break.
    return worldRef.current.playerHasItems(itemKeys);
  }
    const playerHasSignals = (signal) => { // <- ^ this seems hacky, should the paths themselves carry these methods? that way they can all be passed?
    return worldRef.current.playerHasSignals(signal);
  }

  // let world = worldRef.current;

  return (
    <div id="playScreen">
      <h1><Link id="backToTitle" to='/'>Old Cove</Link></h1>
      <Information world={worldRef.current} handleChange={handleChange}/>
      <Choices paths={worldRef.current.getPaths()} items={worldRef.current.items} lastPosition={worldRef.current.position.lastLocation} playerHasItems={playerHasItems} playerHasSignals={playerHasSignals} handleChange={handleChange}/>
      {/* <GoogleAd/> */}
    </div>
  )
}

export default Game;